# Seeed XIAO nRF52840 (Sense)  ->  board: xiao_ble/nrf52840/sense
CONFIG_BT_DEVICE_NAME="omi-xiao52"

# nRF (BT_LL_SW_SPLIT) controller throughput knobs
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
